
import { Family, HistoricalEvent } from './types';

export const INITIAL_YEAR = 1215;
export const MAX_YEAR = 1450; // Extended max year based on new data

const WIKIMEDIA_BASE = "https://commons.wikimedia.org/wiki/Special:FilePath";

export const SESTI_LIST = [
  "Porta al Prato",
  "Santa Maria Novella",
  "San Giovanni",
  "San Pier Maggiore",
  "Borgo Santi Apostoli",
  "San Scheraggio",
  "Santa Croce",
  "Oltrarno"
];

export const ACADEMIC_MAP_DATA = [
  { id: "1", name: "Abati", grid: "2C" },
  { id: "2", name: "Acciaiuoli", grid: "4B" },
  { id: "3", name: "Adimari", grid: "2C" }, // Map says 2CD, simplistic center at 2C
  { id: "4", name: "Agli", grid: "2B" },
  { id: "5", name: "Alberti", grid: "5F" }, // Map says 5-6F
  { id: "6", name: "Albizzi", grid: "3F" },
  { id: "7", name: "Altoviti", grid: "3F" }, // Shared with 4B
  { id: "8", name: "Amidei", grid: "5C" },
  { id: "9", name: "Ardinghelli", grid: "4B" },
  { id: "10", name: "Barbadori", grid: "5B" },
  { id: "11", name: "Bardi", grid: "6C" },
  { id: "12", name: "Baroncelli", grid: "4D" },
  { id: "13", name: "Buondelmonti", grid: "4B" }, // Map says 4BC
  { id: "14", name: "Canigiani", grid: "7D" },
  { id: "15", name: "Caponsacchi", grid: "3C" },
  { id: "16", name: "Capponi", grid: "7D" },
  { id: "17", name: "Castellani", grid: "5D" },
  { id: "18", name: "Cavalcanti", grid: "3C" },
  { id: "19", name: "Cerchi", grid: "3D" }, // Map says 6B, 3D
  { id: "20", name: "Cerretani", grid: "1C" },
  { id: "21", name: "Covoni", grid: "4E" },
  { id: "22", name: "Davanzati", grid: "4B" },
  { id: "23", name: "Della Bella", grid: "3D" }, // 3DE
  { id: "24", name: "Dell'Antella", grid: "4D" },
  { id: "25", name: "Della Tosa", grid: "2C" },
  { id: "26", name: "Donati", grid: "3E" }, // 3DE, 3G
  { id: "27", name: "Foraboschi", grid: "4D" }, // 4-5D
  { id: "28", name: "Frescobaldi", grid: "5A" },
  { id: "29", name: "Galligai", grid: "2C" },
  { id: "30", name: "Giandonati", grid: "4C" }, // 4-5C
  { id: "31", name: "Gianfigliazzi", grid: "4A" },
  { id: "32", name: "Girolami", grid: "4C" }, // 4-5C
  { id: "33", name: "Giugni", grid: "4D" },
  { id: "34", name: "Gondi", grid: "3D" },
  { id: "35", name: "Guicciardini", grid: "6B" },
  { id: "36", name: "Infangati", grid: "4C" }, // 4CD
  { id: "37", name: "Magalotti", grid: "4E" },
  { id: "38", name: "Mannelli", grid: "6B" },
  { id: "39", name: "Medici", grid: "2C" }, // 2-3C
  { id: "40", name: "Mozzi", grid: "7E" },
  { id: "41", name: "Nerli", grid: "6B" },
  { id: "42", name: "Pazzi", grid: "3E" }, // 3E, 3F
  { id: "43", name: "Peruzzi", grid: "4F" }, // 4-5F
  { id: "44", name: "Pitti", grid: "6B" },
  { id: "45", name: "Ricci", grid: "3D" },
  { id: "46", name: "Ridolfi", grid: "5B" }, // 5-6B
  { id: "47", name: "Rondinelli", grid: "3C" },
  { id: "48", name: "Rossi", grid: "6B" },
  { id: "49", name: "Rucellai", grid: "3A" },
  { id: "50", name: "Sacchetti", grid: "4E" },
  { id: "51", name: "Salviati", grid: "3G" },
  { id: "52", name: "Sassetti", grid: "3B" },
  { id: "53", name: "Scali", grid: "4B" },
  { id: "54", name: "Soldanieri", grid: "4B" }, // 2A, 4B
  { id: "55", name: "Spini", grid: "4A" },
  { id: "56", name: "Strozzi", grid: "3B" }, // 3BC
  { id: "57", name: "Tornaquinci", grid: "3B" }, // 3BC
  { id: "58", name: "Tosinghi", grid: "2C" },
  { id: "59", name: "Uberti", grid: "4D" },
  { id: "60", name: "Visdomini", grid: "2D" },
  { id: "61", name: "Vecchietti", grid: "3B" },
  { id: "62", name: "Velluti", grid: "6A" }
];

export const INITIAL_DATASET: Family[] = [
  {
    id: "ABATI_01",
    name: "Abati",
    branchId: "Main",
    status1Year: 1176,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1260,
    faction1Type: "Ghibelline",
    faction2Year: 1304,
    faction2Type: "Ghibelline",
    subFaction: "White",
    originalSourceTerm: "Elite; Grandi; Ghibelline; cavalieri aureati; consul",
    sourceCitation: "1, 2",
    originalFaction: "Ghibelline",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_abati.svg`,
    mapId: 1,
    gridLocations: ["2C"],
    sesto: "Porta al Prato",
    coordinates: { x: 35, y: 30 }
  },
  {
    id: "ADIMARI_01",
    name: "Adimari",
    branchId: "Main",
    status1Year: 1241,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1260,
    faction1Type: "Guelf",
    faction2Year: 1343,
    faction2Type: "Guelf",
    subFaction: "White",
    originalSourceTerm: "Ancient lineage; Grandi; Guelfi; Knight; Noble Guelf citizen",
    sourceCitation: "01-Jul",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_adimari.svg`,
    mapId: 3,
    gridLocations: ["2C", "2D"],
    sesto: "San Giovanni",
    coordinates: { x: 48, y: 32 }
  },
  {
    id: "ALBERTI_001",
    name: "Alberti",
    branchId: "Main",
    status1Year: 1250,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1360,
    faction1Type: "Guelf",
    faction2Year: 1393,
    faction2Type: "Guelf",
    subFaction: "None",
    originalSourceTerm: "Grandi; Wealthiest merchant families; professional scribe",
    sourceCitation: "08-Oct",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_alberti.svg`,
    mapId: 5,
    gridLocations: ["5F", "6F"],
    sesto: "Santa Croce",
    coordinates: { x: 75, y: 70 }
  },
  {
    id: "ALBIZZI_01",
    name: "Albizzi",
    branchId: "Main",
    status1Year: 1280,
    status1Class: "Popolo",
    isMagnate: false,
    status2Year: 1381,
    status2Class: "Popolo Grasso",
    faction1Year: 1300,
    faction1Type: "Guelf",
    faction2Year: 1412,
    faction2Type: "Guelf",
    subFaction: "Black",
    originalSourceTerm: "Merchant family; New plutocracy; Black Guelf; Popular nobles",
    sourceCitation: "1, 4, 11-14",
    originalFaction: "Guelf",
    originalStatus: "Popolo",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_albizzi.svg`,
    mapId: 6,
    gridLocations: ["3F"],
    sesto: "San Pier Maggiore",
    coordinates: { x: 72, y: 45 }
  },
  {
    id: "ALIGH_01",
    name: "Alighieri",
    branchId: "Main",
    status1Year: 1265,
    status1Class: "Noble",
    isMagnate: false,
    status2Year: 1300,
    status2Class: "Popolo",
    faction1Year: 1300,
    faction1Type: "Guelf",
    faction2Year: 1302,
    faction2Type: "Ghibelline",
    subFaction: "White",
    originalSourceTerm: "Cavaliere, Priors, Ghibellino fiero",
    sourceCitation: "15, 16",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_alighieri.svg`,
    // Not explicitly in Key to Map 1, but historically near San Pier Maggiore/Santa Croce
    gridLocations: ["3D"], 
    sesto: "San Pier Maggiore",
    coordinates: { x: 58, y: 42 }
  },
  {
    id: "AMIDEI_01",
    name: "Amidei",
    branchId: "Main",
    status1Year: 1216,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1216,
    faction1Type: "Ghibelline",
    faction2Year: 1267,
    faction2Type: "Ghibelline",
    subFaction: "None",
    originalSourceTerm: "Elite; Grandi; Ghibelline",
    sourceCitation: "1",
    originalFaction: "Ghibelline",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_amidei.svg`,
    mapId: 8,
    gridLocations: ["5C"],
    sesto: "San Scheraggio"
  },
  {
    id: "BARDI_01",
    name: "Bardi",
    branchId: "Main",
    status1Year: 1250,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1250,
    faction1Type: "Guelf",
    faction2Year: 1342,
    faction2Type: "Guelf",
    subFaction: "Black",
    originalSourceTerm: "Elite; Grandi; Banchieri; Magnati per accidente; Knight",
    sourceCitation: "1-8, 11, 13, 14, 16, 17",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_bardi.svg`,
    mapId: 11,
    gridLocations: ["6C"],
    sesto: "Oltrarno",
    coordinates: { x: 40, y: 80 }
  },
  {
    id: "BARUCCI_01",
    name: "Barucci",
    branchId: "Main",
    status1Year: 1226,
    status1Class: "Noble",
    isMagnate: false,
    status2Year: 1380,
    status2Class: "Popolo Grasso",
    faction1Year: 1226,
    faction1Type: "Ghibelline",
    faction2Year: 1380,
    faction2Type: "Guelf",
    subFaction: "None",
    originalSourceTerm: "Old Florentine family; Ghibellines who switched; Wool merchants",
    sourceCitation: "10",
    originalFaction: "Ghibelline",
    originalStatus: "Noble",
  },
  {
    id: "BOSTICHI_01",
    name: "Bostichi",
    branchId: "Not in source",
    status1Year: 1301,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1301,
    faction1Type: "Guelf",
    faction2Year: 1301,
    faction2Type: "Guelf",
    subFaction: "Black",
    originalSourceTerm: "Grandi, Black Guelf",
    sourceCitation: "04-Jun",
    originalFaction: "Guelf",
    originalStatus: "Noble",
  },
  {
    id: "BUL_01",
    name: "Bulgarini",
    branchId: "Main",
    status1Year: 1200,
    status1Class: "Noble",
    isMagnate: false,
    status2Year: 1478,
    status2Class: "Noble",
    faction1Year: undefined,
    faction1Type: "Not in source",
    faction2Year: undefined,
    faction2Type: "Not in source",
    subFaction: "None",
    originalSourceTerm: "noble Sienese family; châtelain",
    sourceCitation: "9",
    originalFaction: "Not in source",
    originalStatus: "Noble",
  },
  {
    id: "BUONDELMONTI_01",
    name: "Buondelmonti",
    branchId: "Main",
    status1Year: 1215,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1215,
    faction1Type: "Guelf",
    faction2Year: 1342,
    faction2Type: "Guelf",
    subFaction: "Black",
    originalSourceTerm: "Ancient lineage; Grandi; Guelfi; chavaliere; Milites",
    sourceCitation: "1-3, 7, 8, 11, 18",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_buondelmonti.svg`,
    mapId: 13,
    gridLocations: ["4B", "4C"],
    sesto: "Borgo Santi Apostoli",
    coordinates: { x: 42, y: 55 }
  },
  {
    id: "CASTELLANI_01",
    name: "Castellani",
    branchId: "Not in source",
    status1Year: 1397,
    status1Class: "Popolo Grasso",
    isMagnate: false,
    status2Year: 1414,
    status2Class: "Popolo Grasso",
    faction1Year: 1397,
    faction1Type: "Guelf",
    faction2Year: 1414,
    faction2Type: "Guelf",
    subFaction: "None",
    originalSourceTerm: "Guelph faction",
    sourceCitation: "12",
    originalFaction: "Guelf",
    originalStatus: "Popolo Grasso",
    mapId: 17,
    gridLocations: ["5D"],
    sesto: "Santa Croce"
  },
  {
    id: "CAVALCANTI_01",
    name: "Cavalcanti",
    branchId: "Main",
    status1Year: 1200,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1267,
    faction1Type: "Guelf",
    faction2Year: 1304,
    faction2Type: "Guelf",
    subFaction: "White",
    originalSourceTerm: "Old Guelf elite; Magnati; Grandi; Noble knight",
    sourceCitation: "1, 3, 4, 6-8, 13",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_cavalcanti.svg`,
    mapId: 18,
    gridLocations: ["3C"],
    sesto: "Santa Maria Novella",
    coordinates: { x: 38, y: 45 }
  },
  {
    id: "CERCHI_01",
    name: "Cerchi",
    branchId: "Main",
    status1Year: 1215,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1215,
    faction1Type: "Guelf",
    faction2Year: 1301,
    faction2Type: "Guelf",
    subFaction: "White",
    originalSourceTerm: "Newer merchant family; Magnati per accidente; White party heads",
    sourceCitation: "1-5, 7, 11, 13, 17, 19",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_cerchi.svg`,
    mapId: 19,
    gridLocations: ["6B", "3D"],
    sesto: "San Pier Maggiore",
    coordinates: { x: 55, y: 38 }
  },
  {
    id: "CORBIZZI_01",
    name: "Corbizzi",
    branchId: "Not in source",
    status1Year: 1380,
    status1Class: "Popolo",
    isMagnate: false,
    status2Year: 1400,
    status2Class: "Popolo",
    faction1Year: 1380,
    faction1Type: "Guelf",
    faction2Year: 1400,
    faction2Type: "Guelf",
    subFaction: "None",
    originalSourceTerm: "Confidant of those in power",
    sourceCitation: "12",
    originalFaction: "Guelf",
    originalStatus: "Popolo",
  },
  {
    id: "DATI_01",
    name: "Dati",
    branchId: "Not in source",
    status1Year: 1384,
    status1Class: "Popolo Grasso",
    isMagnate: false,
    status2Year: 1412,
    status2Class: "Popolo Grasso",
    faction1Year: 1250,
    faction1Type: "Guelf",
    faction2Year: 1306,
    faction2Type: "Guelf",
    subFaction: "None",
    originalSourceTerm: "Companies",
    sourceCitation: "20",
    originalFaction: "Guelf",
    originalStatus: "Popolo Grasso",
  },
  {
    id: "DELLA_BELLA_01",
    name: "Della Bella",
    branchId: "Main",
    status1Year: 1293,
    status1Class: "Popolo",
    isMagnate: false,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1293,
    faction1Type: "Guelf",
    faction2Year: undefined,
    faction2Type: "Not in source",
    subFaction: "None",
    originalSourceTerm: "Noble lineage but a lover of the freedom; Popolani",
    sourceCitation: "11",
    originalFaction: "Guelf",
    originalStatus: "Popolo",
    mapId: 23,
    gridLocations: ["3D", "3E"],
    sesto: "San Pier Maggiore"
  },
  {
    id: "DONATI_01",
    name: "Donati",
    branchId: "Main",
    status1Year: 1215,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1215,
    faction1Type: "Guelf",
    faction2Year: 1301,
    faction2Type: "Guelf",
    subFaction: "Black",
    originalSourceTerm: "Ancient lineage; Grandi; Black party heads; Barone",
    sourceCitation: "1-5, 7, 8, 11, 18, 19",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_donati.svg`,
    mapId: 26,
    gridLocations: ["3D", "3E", "3G"],
    sesto: "San Pier Maggiore",
    coordinates: { x: 65, y: 40 }
  },
  {
    id: "FRESCOBALDI_01",
    name: "Frescobaldi",
    branchId: "Main",
    status1Year: 1250,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1267,
    faction1Type: "Guelf",
    faction2Year: 1340,
    faction2Type: "Guelf",
    subFaction: "White",
    originalSourceTerm: "Elite; Banchieri; Magnate; Knight; Grandi",
    sourceCitation: "1, 4-7, 13, 16, 17",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_frescobaldi.svg`,
    mapId: 28,
    gridLocations: ["5A"],
    sesto: "Oltrarno",
    coordinates: { x: 25, y: 60 }
  },
  {
    id: "GIANFIGLIAZZI_01",
    name: "Gianfigliazzi",
    branchId: "Not in source",
    status1Year: 1378,
    status1Class: "Popolo Grasso",
    isMagnate: false,
    status2Year: 1414,
    status2Class: "Popolo Grasso",
    faction1Year: 1378,
    faction1Type: "Guelf",
    faction2Year: 1414,
    faction2Type: "Guelf",
    subFaction: "None",
    originalSourceTerm: "Guelph citizens",
    sourceCitation: "12",
    originalFaction: "Guelf",
    originalStatus: "Popolo Grasso",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_gianfigliazzi.svg`,
    mapId: 31,
    gridLocations: ["4A"],
    sesto: "Santa Maria Novella"
  },
  {
    id: "GIROLAMI_01",
    name: "Girolami",
    branchId: "Salvi",
    status1Year: 1282,
    status1Class: "Popolo",
    isMagnate: false,
    status2Year: 1293,
    status2Class: "Popolo Grasso",
    faction1Year: 1282,
    faction1Type: "Guelf",
    faction2Year: 1300,
    faction2Type: "Guelf",
    subFaction: "White",
    originalSourceTerm: "Popolani, Popolani Grassi",
    sourceCitation: "7",
    originalFaction: "Guelf",
    originalStatus: "Popolo",
    mapId: 32,
    gridLocations: ["4C", "5C"],
    sesto: "San Scheraggio"
  },
  {
    id: "ISCERMI_01",
    name: "Iscermi",
    branchId: "Monna Lapa",
    status1Year: 1270,
    status1Class: "Noble",
    isMagnate: false,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1270,
    faction1Type: "Guelf",
    faction2Year: undefined,
    faction2Type: "Not in source",
    subFaction: "None",
    originalSourceTerm: "Old noble Guelph family",
    sourceCitation: "10",
    originalFaction: "Guelf",
    originalStatus: "Noble",
  },
  {
    id: "LAMBERTI_01",
    name: "Lamberti",
    branchId: "Main",
    status1Year: 1216,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1216,
    faction1Type: "Ghibelline",
    faction2Year: 1267,
    faction2Type: "Ghibelline",
    subFaction: "None",
    originalSourceTerm: "Grandi; Ghibelline",
    sourceCitation: "1",
    originalFaction: "Ghibelline",
    originalStatus: "Noble",
  },
  {
    id: "MANCINI_01",
    name: "Mancini",
    branchId: "Main",
    status1Year: 1284,
    status1Class: "Popolo",
    isMagnate: false,
    status2Year: 1447,
    status2Class: "Popolo Grasso",
    faction1Year: undefined,
    faction1Type: "Not in source",
    faction2Year: undefined,
    faction2Type: "Not in source",
    subFaction: "None",
    originalSourceTerm: "ruling family; prominent statesman",
    sourceCitation: "9",
    originalFaction: "Not in source",
    originalStatus: "Popolo",
  },
  {
    id: "MEDICI_01",
    name: "Medici",
    branchId: "Main",
    status1Year: 1250,
    status1Class: "Popolo",
    isMagnate: false,
    status2Year: 1434,
    status2Class: "Popolo Grasso",
    faction1Year: 1300,
    faction1Type: "Guelf",
    faction2Year: 1434,
    faction2Type: "Guelf",
    subFaction: "White",
    originalSourceTerm: "Popolani; Noble popular family; Great merchants",
    sourceCitation: "3, 4, 6, 8, 11-13",
    originalFaction: "Guelf",
    originalStatus: "Popolo",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Armoiries_famille_It_M%C3%A9dicis_(6_boules).svg`,
    mapId: 39,
    gridLocations: ["2C", "3C"],
    sesto: "San Giovanni",
    coordinates: { x: 45, y: 35 }
  },
  {
    id: "MORELLI_01",
    name: "Morelli",
    branchId: "Main",
    status1Year: 1284,
    status1Class: "Popolo Grasso",
    isMagnate: false,
    status2Year: 1347,
    status2Class: "Popolo Grasso",
    faction1Year: 1300,
    faction1Type: "Guelf",
    faction2Year: 1347,
    faction2Type: "Guelf",
    subFaction: "Black",
    originalSourceTerm: "Consul of the Wool Guild; True and legitimate Guelph",
    sourceCitation: "10",
    originalFaction: "Guelf",
    originalStatus: "Popolo Grasso",
  },
  {
    id: "PAZZI_01",
    name: "Pazzi",
    branchId: "Main",
    status1Year: 1289,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1289,
    faction1Type: "Guelf",
    faction2Year: 1301,
    faction2Type: "Guelf",
    subFaction: "Black",
    originalSourceTerm: "Ancient lineage; Knight; Grandi",
    sourceCitation: "4-7, 19",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_pazzi.svg`,
    mapId: 42,
    gridLocations: ["3E", "3F"],
    sesto: "San Pier Maggiore"
  },
  {
    id: "PERUZZI_01",
    name: "Peruzzi",
    branchId: "Main",
    status1Year: 1280,
    status1Class: "Popolo Grasso",
    isMagnate: false,
    status2Year: 1300,
    status2Class: "Noble",
    faction1Year: 1300,
    faction1Type: "Guelf",
    faction2Year: 1420,
    faction2Type: "Guelf",
    subFaction: "Black",
    originalSourceTerm: "Merchant family; Popolani (non-magnate elite); Guelph faction",
    sourceCitation: "1, 3, 12",
    originalFaction: "Guelf",
    originalStatus: "Popolo Grasso",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_peruzzi.svg`,
    mapId: 43,
    gridLocations: ["4F", "5F"],
    sesto: "Santa Croce"
  },
  {
    id: "PITTI_01",
    name: "Pitti",
    branchId: "Luiano",
    status1Year: 1202,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: 1412,
    status2Class: "Noble",
    faction1Year: 1202,
    faction1Type: "Guelf",
    faction2Year: 1402,
    faction2Type: "Guelf",
    subFaction: "None",
    originalSourceTerm: "Guelphs (driven from Semifonte)",
    sourceCitation: "12",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_pitti.svg`,
    mapId: 44,
    gridLocations: ["6B"],
    sesto: "Oltrarno",
    coordinates: { x: 35, y: 75 }
  },
  {
    id: "QUARATESI_01",
    name: "Quaratesi",
    branchId: "Main",
    status1Year: 1363,
    status1Class: "Popolo Grasso",
    isMagnate: false,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1363,
    faction1Type: "Guelf",
    faction2Year: undefined,
    faction2Type: "Not in source",
    subFaction: "Black",
    originalSourceTerm: "Prominent family in Black Guelph faction",
    sourceCitation: "10",
    originalFaction: "Guelf",
    originalStatus: "Popolo Grasso",
  },
  {
    id: "RICASOLI_01",
    name: "Ricasoli",
    branchId: "Fibindacci",
    status1Year: 1380,
    status1Class: "Popolo",
    isMagnate: false,
    status2Year: 1412,
    status2Class: "Popolo",
    faction1Year: 1380,
    faction1Type: "Guelf",
    faction2Year: 1412,
    faction2Type: "Guelf",
    subFaction: "None",
    originalSourceTerm: "Popolani (became in 1380)",
    sourceCitation: "12",
    originalFaction: "Guelf",
    originalStatus: "Popolo",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_ricasoli.svg`,
  },
  {
    id: "RICCI_01",
    name: "Ricci",
    branchId: "Main",
    status1Year: 1350,
    status1Class: "Popolo",
    isMagnate: false,
    status2Year: 1381,
    status2Class: "Popolo Grasso",
    faction1Year: 1350,
    faction1Type: "Guelf",
    faction2Year: 1397,
    faction2Type: "Guelf",
    subFaction: "White",
    originalSourceTerm: "Popolani grassi; Powerful family; White Guelph faction",
    sourceCitation: "8, 10, 11",
    originalFaction: "Guelf",
    originalStatus: "Popolo",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_ricci.svg`,
    mapId: 45,
    gridLocations: ["3D"],
    sesto: "San Giovanni"
  },
  {
    id: "ROSSI_01",
    name: "Rossi",
    branchId: "Main",
    status1Year: 1301,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1301,
    faction1Type: "Guelf",
    faction2Year: 1343,
    faction2Type: "Guelf",
    subFaction: "Black",
    originalSourceTerm: "Knight; Black Guelf; Grandi; Honourable family",
    sourceCitation: "3-6, 17",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_rossi_d_oltrarno.svg`,
    mapId: 48,
    gridLocations: ["6B"],
    sesto: "Oltrarno"
  },
  {
    id: "SASSETTI_01",
    name: "Sassetti",
    branchId: "Main",
    status1Year: 1447,
    status1Class: "Popolo Grasso",
    isMagnate: false,
    status2Year: 1462,
    status2Class: "Popolo Grasso",
    faction1Year: undefined,
    faction1Type: "Not in source",
    faction2Year: undefined,
    faction2Type: "Not in source",
    subFaction: "None",
    originalSourceTerm: "Medici bank manager; wealthy",
    sourceCitation: "9",
    originalFaction: "Not in source",
    originalStatus: "Popolo Grasso",
    mapId: 52,
    gridLocations: ["3B"],
    sesto: "Santa Maria Novella"
  },
  {
    id: "SODERINI_01",
    name: "Soderini",
    branchId: "Main",
    status1Year: 1378,
    status1Class: "Popolo",
    isMagnate: false,
    status2Year: 1465,
    status2Class: "Popolo",
    faction1Year: undefined,
    faction1Type: "Not in source",
    faction2Year: undefined,
    faction2Type: "Not in source",
    subFaction: "None",
    originalSourceTerm: "Popolani",
    sourceCitation: "8",
    originalFaction: "Not in source",
    originalStatus: "Popolo",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_soderini.svg`,
    // Not in key 1-62 but historically in Oltrarno
    gridLocations: ["6B"],
    sesto: "Oltrarno",
    coordinates: { x: 20, y: 70 }
  },
  {
    id: "SPINI_01",
    name: "Spini",
    branchId: "Not in source",
    status1Year: 1301,
    status1Class: "Noble",
    isMagnate: false,
    status2Year: 1301,
    status2Class: "Noble",
    faction1Year: 1301,
    faction1Type: "Guelf",
    faction2Year: 1301,
    faction2Type: "Guelf",
    subFaction: "Black",
    originalSourceTerm: "Knight, Black Guelf",
    sourceCitation: "04-Jun",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_spini.svg`,
    mapId: 55,
    gridLocations: ["4A"],
    sesto: "Santa Maria Novella"
  },
  {
    id: "STRINATI_01",
    name: "Strinati",
    branchId: "Main",
    status1Year: 1232,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1260,
    faction1Type: "Ghibelline",
    faction2Year: 1311,
    faction2Type: "Ghibelline",
    subFaction: "None",
    originalSourceTerm: "Cavaliere, Magnate, Ghibellini",
    sourceCitation: "19",
    originalFaction: "Ghibelline",
    originalStatus: "Noble",
  },
  {
    id: "STROZZI_01",
    name: "Strozzi",
    branchId: "Main",
    status1Year: 1301,
    status1Class: "Popolo Grasso",
    isMagnate: true,
    status2Year: 1387,
    status2Class: undefined,
    faction1Year: 1301,
    faction1Type: "Guelf",
    faction2Year: 1442,
    faction2Type: "Guelf",
    subFaction: "Black",
    originalSourceTerm: "Popolo Grasso; Magnati; Popular nobles; aristocratic",
    sourceCitation: "4, 8, 9, 11, 13",
    originalFaction: "Guelf",
    originalStatus: "Popolo Grasso",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Stemma_Strozzi.svg`,
    mapId: 56,
    gridLocations: ["3B", "3C"],
    sesto: "Santa Maria Novella",
    coordinates: { x: 30, y: 40 }
  },
  {
    id: "TOSA_01",
    name: "della Tosa",
    branchId: "General Lineage",
    status1Year: 1127,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1286,
    faction1Type: "Guelf",
    faction2Year: 1301,
    faction2Type: "Guelf",
    subFaction: "None",
    originalSourceTerm: "Ancient branch of Visdomini; Noble",
    sourceCitation: "2",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_tosinghi.svg`,
    mapId: 25,
    gridLocations: ["2C"],
    sesto: "San Giovanni"
  },
  {
    id: "TORNAQUINCI_01",
    name: "Tornaquinci",
    branchId: "Not in source",
    status1Year: 1301,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1301,
    faction1Type: "Guelf",
    faction2Year: 1301,
    faction2Type: "Guelf",
    subFaction: "Black",
    originalSourceTerm: "Grandi, Black Guelf, Clan",
    sourceCitation: "04-Jun",
    originalFaction: "Guelf",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_tornaquinci.svg`,
    mapId: 57,
    gridLocations: ["3B", "3C"],
    sesto: "Santa Maria Novella"
  },
  {
    id: "UBALDINI_01",
    name: "Ubaldini",
    branchId: "Main",
    status1Year: 1250,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1250,
    faction1Type: "Ghibelline",
    faction2Year: undefined,
    faction2Type: "Not in source",
    subFaction: "None",
    originalSourceTerm: "Tyrannical Ubaldini; Ghibellines; Lords of the Mugello",
    sourceCitation: "10",
    originalFaction: "Ghibelline",
    originalStatus: "Noble",
  },
  {
    id: "UBERTI_01",
    name: "Uberti",
    branchId: "Main",
    status1Year: 1177,
    status1Class: "Noble",
    isMagnate: true,
    status2Year: undefined,
    status2Class: undefined,
    faction1Year: 1177,
    faction1Type: "Ghibelline",
    faction2Year: 1280,
    faction2Type: "Ghibelline",
    subFaction: "None",
    originalSourceTerm: "Ancient Lineage; Grandi; Noble and Powerful; consul",
    sourceCitation: "1-3, 7, 8, 11, 18",
    originalFaction: "Ghibelline",
    originalStatus: "Noble",
    coatOfArmsUrl: `${WIKIMEDIA_BASE}/Coa_fam_ITA_uberti.svg`,
    mapId: 59,
    gridLocations: ["4D"],
    sesto: "San Scheraggio",
    coordinates: { x: 50, y: 50 }
  },
  {
    id: "UBERTINI_01",
    name: "Ubertini",
    branchId: "Not in source",
    status1Year: 1407,
    status1Class: "Noble",
    isMagnate: false,
    status2Year: 1423,
    status2Class: "Noble",
    faction1Year: 1407,
    faction1Type: "Ghibelline",
    faction2Year: 1423,
    faction2Type: "Ghibelline",
    subFaction: "None",
    originalSourceTerm: "Rebellion against Florence",
    sourceCitation: "12",
    originalFaction: "Ghibelline",
    originalStatus: "Noble",
  },
  {
    id: "VELLUTI_01",
    name: "Velluti",
    branchId: "Main",
    status1Year: 1244,
    status1Class: "Popolo",
    isMagnate: false,
    status2Year: 1341,
    status2Class: "Popolo Grasso",
    faction1Year: 1280,
    faction1Type: "Guelf",
    faction2Year: undefined,
    faction2Type: "Not in source",
    subFaction: "Not in source",
    originalSourceTerm: "Mersatantia, Priors",
    sourceCitation: "17, 19",
    originalFaction: "Guelf",
    originalStatus: "Popolo",
    mapId: 62,
    gridLocations: ["6A"],
    sesto: "Oltrarno",
    coordinates: { x: 15, y: 80 }
  },
];

export const EVENTS: HistoricalEvent[] = [
  { 
    year: 1216, 
    title: "Buondelmonti Murder", 
    shortDescription: "The assassination on the Ponte Vecchio sparks the initial divide between Guelphs and Ghibellines.",
    fullDescription: "On Easter morning, Buondelmonte de' Buondelmonti was brutally murdered at the foot of the statue of Mars on the Ponte Vecchio. This act of violence, carried out by the Amidei and their allies in retaliation for a broken marriage contract, is traditionally cited by chroniclers like Giovanni Villani as the spark that ignited the factional conflict between the Guelphs and Ghibellines in Florence.",
    sources: [
        { title: "Giovanni Villani, 'Nuova Cronica'", quote: "And thus began the accursed Guelf and Ghibelline parties in Florence." },
        { title: "Dante Alighieri, 'Divine Comedy' (Paradiso XVI)", quote: "O Buondelmonte, how ill didst thou flee its nuptials at the prompting of another!" }
    ]
  },
  { 
    year: 1260, 
    title: "Battle of Montaperti", 
    shortDescription: "A crushing Ghibelline victory over the Guelphs, forcing many families into exile.",
    fullDescription: "The bloodiest battle in medieval Tuscany, fought near Siena. The Florentine Ghibellines, aided by King Manfred of Sicily, decimated the Guelph army of Florence. The river Arbia was said to be 'colored red' with blood. Following this defeat, the Ghibellines took control of Florence, destroying the houses of leading Guelphs and forcing them into exile.",
    sources: [
        { title: "Dante Alighieri, 'Inferno' (Canto X)", quote: "The havoc and the great slaughter, which dyed the Arbia red..." },
        { title: "Giovanni Villani, 'Nuova Cronica'", quote: "The defeat was such that only the night put an end to the pursuit." }
    ]
  },
  { 
    year: 1266, 
    title: "Battle of Benevento", 
    shortDescription: "Charles of Anjou defeats Manfred. Ghibellines are expelled, Guelphs return.",
    fullDescription: "The defeat and death of King Manfred of Sicily at the hands of Charles of Anjou marked the collapse of Imperial power in Italy. In Florence, this led to the overthrow of the Ghibelline regime and the triumphant return of the Guelph exiles, who would dominate the city's politics for decades to come.",
    sources: [
        { title: "Leonardo Bruni, 'History of the Florentine People'", quote: "Thus the Ghibelline power, which had seemed invincible, was broken in a single day." }
    ]
  },
  { 
    year: 1293, 
    title: "Ordinances of Justice", 
    shortDescription: "Laws enacted to curb Magnate power, barring them from office.",
    fullDescription: "Spearheaded by Giano della Bella, these revolutionary laws were designed to check the violence and arrogance of the magnate families. They established the office of the Gonfaloniere of Justice, required nobles to enroll in a guild to hold office, and imposed severe penalties for attacks on commoners.",
    sources: [
        { title: "Dino Compagni, 'Cronica'", quote: "The citizens determined to make laws that would curb the power of the great." },
        { title: "Najemy, 'A History of Florence'", quote: "The Ordinances defined the political identity of the guild community." }
    ]
  },
  { 
    year: 1300, 
    title: "The Schism", 
    shortDescription: "Internal rivalry splits the Guelphs into 'Black' and 'White' factions.",
    fullDescription: "With the Ghibellines defeated, the ruling Guelph party fractured into two warring camps: the Blacks (led by the Donati, staunch allies of the Pope) and the Whites (led by the Cerchi, favoring more independence). This internecine conflict tore the city apart, leading to street fighting and political assassinations.",
    sources: [
        { title: "Dino Compagni, 'Cronica'", quote: "The city was divided: and the division arose from the sin of ingratitude." },
        { title: "Dante Alighieri", quote: "The divided city." }
    ]
  },
  { 
    year: 1302, 
    title: "Exile of Whites", 
    shortDescription: "The Black Guelphs seize control, exiling the Whites, including Dante.",
    fullDescription: "With the support of Pope Boniface VIII and Charles of Valois, the Black Guelphs staged a coup, violently purging the city of their White rivals. Hundreds were condemned to death or exile, including the poet Dante Alighieri, who would never see his beloved Florence again.",
    sources: [
        { title: "Barbero, 'Dante'", quote: "Dante was condemned to be burned at the stake if he ever returned to Florence." }
    ]
  },
  { 
    year: 1348, 
    title: "Black Death", 
    shortDescription: "The plague devastates Florence, killing nearly half the population.",
    fullDescription: "The bubonic plague arrived in Florence, causing catastrophic loss of life. Chroniclers estimate that up to 60% of the population perished. This demographic collapse fundamentally altered the social and economic structure of the city, creating labor shortages and shifting wealth concentration.",
    sources: [
        { title: "Boccaccio, 'Decameron'", quote: "How many valiant men, how many fair ladies, breakfasted with their kin and the same night supped with their ancestors in the other world!" },
        { title: "Giovanni Villani", quote: "And I, Giovanni Villani, wrote this..." }
    ]
  },
  { 
    year: 1378, 
    title: "Ciompi Revolt", 
    shortDescription: "Insurrection by wool carders establishes a brief democratic government.",
    fullDescription: "A violent uprising by the 'Ciompi' (unrepresented wool carders) and other minor guild workers against the oligarchy. They succeeded in briefly taking over the Palazzo della Signoria and establishing a more democratic government, although the revolt was eventually suppressed by the major guilds.",
    sources: [
        { title: "Machiavelli, 'History of Florence'", quote: "The people, to avenge themselves on the nobility, created the Ciompi." },
        { title: "Gene Brucker", quote: "The revolution of the Ciompi was the most democratic experiment in Florentine history." }
    ]
  },
];
